services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agro-api
    env_file:
      - .env
    environment:
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GEN_MODEL=${GEN_MODEL}
      - OLLAMA_URL=${OLLAMA_URL:-}
      - OAUTH_ENABLED=${OAUTH_ENABLED:-false}
      - OAUTH_TOKEN=${OAUTH_TOKEN:-}
      - GIT_BRANCH=${GIT_BRANCH}
    ports:
      - "8012:8012"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.env:/app/.env
      - ./repos.json:/app/repos.json
      - ./out:/app/out
      - ./data:/app/data
      - ./gui:/app/gui
      - ./server:/app/server
    profiles: ["api"]

  mcp-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-service-mcp-http
    command: python -m server.mcp.http
    environment:
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    ports:
      - "8013:8013"
    profiles: ["mcp-http"]

  mcp-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: rag-service-node
    environment:
      - RAG_API_URL=${RAG_API_URL:-http://api:8012}
      - PORT=8014
    ports:
      - "8014:8014"
    depends_on:
      - api
    profiles: ["node"]
