apiVersion: 1

# Fixed indentation for the list under datasources
# (YAML requires a space before the dash for list items)
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$$${__value.raw}"
